FROM lynnard/reflex-cocos2d-android-builder

# use like this: docker run --rm -v `pwd`:/hs image_tag [make_target]
ENTRYPOINT ["/nix-build-ghc-android-runner", "--", "make", "-C", "/hs", "TARGET=android"]

# add additional packages by
# RUN /nix-build-ghc-android-runner --arg extraGhcPkgs 'p: [ p.MonadPrompt ]'

COPY . /hs
